import { Inter, Rubik, Lora } from 'next/font/google'
import './globals.css'
import localFont from 'next/font/local'
import Cursor from './utils/Cursor'

const inter = Inter({ subsets: ['latin'] })
const rubik = Rubik({ subsets: ['latin'] })
const lora = Lora({ subsets: ['latin'] })
const microsoftSansSerif = localFont({ src: './micross.ttf' })

export const metadata = {
  title: 'Ralph Chang 2023 portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>{children}</body>
    </html>
  )
}
